from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(860, 445)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/lock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBox = QtWidgets.QTextEdit(self.centralwidget)
        self.textBox.setGeometry(QtCore.QRect(280, 0, 561, 381))
        self.textBox.setObjectName("textBox")
        self.Icon1 = QtWidgets.QLabel(self.centralwidget)
        self.Icon1.setGeometry(QtCore.QRect(50, 20, 131, 111))
        self.Icon1.setText("")
        self.Icon1.setPixmap(QtGui.QPixmap("resources/soldier.png"))
        self.Icon1.setScaledContents(True)
        self.Icon1.setObjectName("Icon1")
        self.Icon2 = QtWidgets.QLabel(self.centralwidget)
        self.Icon2.setGeometry(QtCore.QRect(160, 70, 41, 41))
        self.Icon2.setText("")
        self.Icon2.setPixmap(QtGui.QPixmap("resources/lock.png"))
        self.Icon2.setScaledContents(True)
        self.Icon2.setObjectName("Icon2")
        self.encryptButton = QtWidgets.QPushButton(self.centralwidget)
        self.encryptButton.setGeometry(QtCore.QRect(20, 270, 241, 34))
        self.encryptButton.setObjectName("encryptButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 140, 231, 31))
        font = QtGui.QFont()
        font.setFamily("C059 [UKWN]")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.decryptButton = QtWidgets.QPushButton(self.centralwidget)
        self.decryptButton.setGeometry(QtCore.QRect(20, 310, 241, 34))
        self.decryptButton.setObjectName("decryptButton")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(20, 350, 241, 34))
        self.exitButton.setObjectName("exitButton")
        self.openButton = QtWidgets.QPushButton(self.centralwidget)
        self.openButton.setGeometry(QtCore.QRect(20, 190, 241, 34))
        self.openButton.setObjectName("openButton")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(20, 230, 241, 34))
        self.saveButton.setObjectName("saveButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 860, 30))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDescription = QtWidgets.QAction(MainWindow)
        self.actionDescription.setObjectName("actionDescription")
        self.actionIcon_Attributions = QtWidgets.QAction(MainWindow)
        self.actionIcon_Attributions.setObjectName("actionIcon_Attributions")
        self.actionHow_to_Use = QtWidgets.QAction(MainWindow)
        self.actionHow_to_Use.setObjectName("actionHow_to_Use")
        self.menuHelp.addAction(self.actionHow_to_Use)
        self.menuAbout.addAction(self.actionDescription)
        self.menuAbout.addAction(self.actionIcon_Attributions)
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple Text Lockbox"))
        self.encryptButton.setText(_translate("MainWindow", "Encrypt Contents"))
        self.label.setText(_translate("MainWindow", "Simple Text Lockbox"))
        self.decryptButton.setText(_translate("MainWindow", "Decrypt Contents"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.openButton.setText(_translate("MainWindow", "Open"))
        self.saveButton.setText(_translate("MainWindow", "Save Contents"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionDescription.setText(_translate("MainWindow", "Description"))
        self.actionIcon_Attributions.setText(_translate("MainWindow", "Icon Attributions"))
        self.actionHow_to_Use.setText(_translate("MainWindow", "How to Use"))

